[package]
name = "venx"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
    "easy_compute",
    "bevy_venx"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy_compute = { path = "./easy_compute"}
glam = "*"
bytemuck = "1.14.0"
bytemuck_derive = "1.5.0"
async-trait = "0.1.73"
bytes-cast = "0.3.0"

anyhow = "1.0.75"
fastanvil = {version = "0.29.0", optional = true}
bitcode = { version = "0.4.0", features = ["derive"] }
pollster = "0.3.0"

log = "0.4.20"
flate2 = "1.0.27"
rand = "0.8.5"
bmp = "0.5.0"

[features]
default = ["gpu", "mca_converter"]
gpu = []
bevy_ecs = []
mca_converter = ["dep:fastanvil"]
