[package]
name = "venx_shaders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
spirv-std = "0.9.0"
venx_core = {path = "../venx_core", features = ["gpu"]}